#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd

path="/etc/passwd"
while IFS=: read -r username userid homedir
do
	echo "$username $userid $homedir" | cut -d: -f 1,3,6
done < $path