#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

n=0

while [ $n -lt 10 ]
do
	if [ $n -eq 3 ]
	then
		echo "bad luck"
	elif [ $n -eq 7 ]
	then
		echo "good luck"
	else
		echo "Holberton School"
	fi
	n=$((n+1))
done