#!/usr/bin/env bash
# Bash script that displays the current directory in a list format and
# where only the part of the name after the first dash is displayed

for i in *
do
	echo "$i" | cut -d "-" -f2
done